### PR TITLE
fix: Incorrect highlighting in navbar

### PR DESCRIPTION
**Pull request by Selflocking**
Before: 
image
After:
image

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Selflocking still not correct in preview:

image

**Comment by Selflocking** [comment]
> @Selflocking still not correct in preview:
> 
> image

It may be because your mouse is hovering over it

**Comment by hsluoyz** [comment]
@Selflocking enter: https://deploy-preview-71--casbin.netlify.app/docs/ide-plugins

You will see "Docs" is highlighted

**Comment by Selflocking** [comment]
> @Selflocking enter: https://deploy-preview-71--casbin.netlify.app/docs/ide-plugins
> 
> You will see "Docs" is highlighted

In my case ''Docs'' is highlighted, but ''IDE Plugins'' is not
image

**Comment by hsluoyz** [comment]
@Selflocking OK, I know what's wrong here. I clicked the top nav button, but it goes to the docs. OK then.

**Pull request merged**
