### PR TITLE
feat: website migrate v1 to v2

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- **This PR is work in progress**
- ref: #1

### CODE REVIEW

**Comment by Shivansh-yadav13** [comment]
@hsluoyz rn I'm getting this issue please take a look 
```shell
[ERROR] ValidationError: "algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration
```

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 plz see the appId in v1: https://github.com/casbin/casbin-website

**Comment by Shivansh-yadav13** [comment]
@hsluoyz `appKey` is only present 

https://github.com/casbin/casbin-website/blob/688081228f17f830dd48c8264803b9432d00b72b/website/siteConfig.js#L56

**Comment by Shivansh-yadav13** [comment]
you can also see this https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

BTW we would also need to update the docs becuase docs does not specify the language now
Screenshot from 2022-05-07 16-10-48

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 

> you can also see this https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

We will create a new app (and index) in Algolia instead of migrating the old one, becasue Casbin v1 site will still exist for long time.

 > BTW we would also need to update the docs becuase docs does not specify the language now

What do you mean by specifying the language?

**Comment by Shivansh-yadav13** [comment]
> What do you mean by specifying the language?

Screenshot from 2022-05-07 19-55-09

Screenshot from 2022-05-07 19-56-27

- In the old website the syntax for each language is shown but after migration it is not showing

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 Docusaurus V2 supported code blocks, but maybe in different syntax, we need to change it if needed.

See: https://docusaurus.io/docs/markdown-features/tabs and https://docusaurus.io/docs/next/markdown-features/code-blocks#custom-magic-comments

image

**Comment by Shivansh-yadav13** [comment]
@hsluoyz I guess we would need to change every `md` file to `mdx` and then use the new way of creating the tabs.
I'm going to work on it and tag you when ready for review.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 yes, plz do that

**Comment by Shivansh-yadav13** [comment]
@hsluoyz I have migrated all the docs to the new style.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 the Algolia info can be:

```json
"algolia": {
      "appId": "6NBEV8TOFK",
      "apiKey": "111e290764eefd6fef64a7113c783afe",
      "indexName": "casbin",
      "contextualSearch": true,
      "searchParameters": {}
    }
```

is this PR done? Because the homepage I saw is:

image

BTW, we have another PR here: https://github.com/casbin/casbin-website/pull/265 what do you think about that PR? Is there any chance that we merge the PR efforts from both of you to deliever the best result?

**Comment by hsluoyz** [comment]
Hi @Shivansh-yadav13 , I decided to use: https://github.com/casbin/casbin-website/pull/265 as a base for this v2 docs repo, because it's more complete, including the nearly finished homepage. But we still have a lof to do, like:

1. Migrate all new commits for v1 after: https://github.com/casbin/casbin-website/pull/265 to this v2 repo.
2. Setup the GitHub pages and deployment pipeline, finally host the docs into: https://docs.casbin.org
3. Upgrade Docusaurus into latest v2 beta release.
4. Integrate anything valuable from your PR into this new codebase.

Can you do this?

image

**Pull request closed without merging**
